-- R u colorful?? cuz i am guys!
require("colors")
-- These are the modules
require("modules/binds")
require("modules/monitors")
require("modules/programs")
require("modules/autostart")
require("modules/env")
require("modules/perms")
require("modules/looknfeel")
require("modules/animations")
require("modules/misc")
require("modules/windowrule")
require("modules/plugins")
require("modules/layouts")
require("modules/input")
require("modules/ecosystem")
